# Generated by Django 4.1 on 2023-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="2000-06-22"),
            preserve_default=False,
        ),
    ]
